version: '3.8'
services:
  betflow-ui:
    container_name: betflow-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
